name: miprimerworkflow
run-name: ${{github.actor }}is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v4
    -uses : actions/set-up-node@v4
    with:
    nod-version: '20'
    - run: npm isnstall -g bash
    - run: bats -v
    
